# 应用服务web访问端口
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studb_new?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    &serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
